#### Aritmética

In [8]:
1 + 1
2 - 1
2.0 * 4
4 / 5
5 ^ 3 # Exponenciación
5 %% 2 # Módulo

[1] 2

[1] 1

[1] 8

[1] 0.8

[1] 125

[1] 1

#### Asignación de variables

In [10]:
x <- 42
x

[1] 42

#### Tipo de dato de una variable

In [18]:
class(4.0)
class(1)
typeof("class")
typeof(TRUE)

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "logical"

#### Vector
Es una estructura unidimensional, del mismo tipo de dato

In [21]:
numeric_vector <- c(1, 10, 49)
numeric_vector
class(numeric_vector)

[1]  1 10 49

[1] "numeric"

In [27]:
some_vector <- c('John Doe', 'Poker Player')
names(some_vector) <- c('Name', 'Profession')
some_vector['Name']
some_vector[1] # Los indices se indexan en 1
some_vector[1:2] # Los : son inclusivos en ambos intervalos, en python es abierto por la derecha

Name 
"John Doe"

Name 
"John Doe"

Name     Profession 
    "John Doe" "Poker Player"

In [29]:
c(1, 2, 3) + c(4, 5, 6) # Suma elemento a elemento
c(1 + 4, 2 + 5, 3 + 6)

[1] 5 7 9

[1] 5 7 9

In [31]:
sum(1:10)

[1] 55

In [33]:
my_nums <- 1:10
my_nums
my_nums[c(1, 3, 8)] # Posiciones en particular

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1 3 8

In [36]:
my_nums[my_nums %% 2 == 1] # Filtró por mascara booleana

[1] 1 3 5 7 9

#### Matrices
Es una colección de elementos del mismo tipo de dato organizados en un número fijo de filas y columnas

In [41]:
A <- matrix(1:9, byrow = TRUE, nrow = 3)
A

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [46]:
B <- matrix(1:7, byrow = TRUE, nrow = 3) # Si la secuencia no completa el número de elementos, el restante se llena con los valores iniciando la secuencia nuevamente
B

Warning message in matrix(1:7, byrow = TRUE, nrow = 3):
“data length [7] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    1    2

In [49]:
# Cifras de 3 peliculas de Star Wars
# Primer elemento, recaudación en taquilla en EE. UU.
# Segundo elemento, recaudación en taquilla fuera de EE. UU.
new_hope <- c(460.998, 314.4)
empire_stikes <- c(290.475, 247.9)
return_jedi <- c(309.306, 165.8)

star_wars_matrix <- matrix(
    c(new_hope, empire_stikes, return_jedi),
    byrow = TRUE,
    nrow = 3
)

star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

In [54]:
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")
colnames(star_wars_matrix) <- c("US", "non-US")
star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

In [57]:
worldwide <- rowSums(star_wars_matrix) # Taquilla Mundial
worldwide
all_star_wars_mat <- cbind(star_wars_matrix, worldwide)
all_star_wars_mat

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

US      non-US worldwide
A New Hope              460.998 314.4  775.398  
The Empire Strikes Back 290.475 247.9  538.375  
Return of the Jedi      309.306 165.8  475.106

In [58]:
all_star_wars_mat[c(1, 3), 2:3]

non-US worldwide
A New Hope         314.4  775.398  
Return of the Jedi 165.8  475.106

In [63]:
all_star_wars_mat
all_star_wars_mat * all_star_wars_mat # La multiplicación es elemento a elemento
all_star_wars_mat * c(1, 2, 3) # La multiplicación se hace por columna
all_star_wars_mat %*% all_star_wars_mat # Multiplicación matricial

US      non-US worldwide
A New Hope              460.998 314.4  775.398  
The Empire Strikes Back 290.475 247.9  538.375  
Return of the Jedi      309.306 165.8  475.106

US        non-US   worldwide
A New Hope              212519.16 98847.36 601242.1 
The Empire Strikes Back  84375.73 61454.41 289847.6 
Return of the Jedi       95670.20 27489.64 225725.7

US      non-US worldwide
A New Hope              460.998 314.4   775.398 
The Empire Strikes Back 580.950 495.8  1076.750 
Return of the Jedi      927.918 497.4  1425.318

US       non-US   worldwide
A New Hope              543679.7 351438.5 895118.3 
The Empire Strikes Back 372439.8 242042.3 614482.1 
Return of the Jedi      337703.3 217120.2 554823.5