In [1]:
import numpy as np
import impyute as impy

In [2]:
n = 5
arr = np.random.uniform(high = 6, size = (n, n))
for _ in range(3):
    arr[np.random.randint(n), np.random.randint(n)] = np.nan

In [4]:
print(arr)

[[1.97860952 4.15253034 4.03488185 2.38174183 3.54909957]
 [5.30015613 3.79080059 2.51822614        nan 1.66449031]
 [5.28799321 1.4315766  1.91238727 3.97139427 0.96457251]
 [1.85237651 1.39289569        nan 3.82835395 1.24835015]
 [4.50877579 5.83016326        nan 3.36832302 3.80344375]]


In [3]:
impy.em(arr)

array([[1.97860952, 4.15253034, 4.03488185, 2.38174183, 3.54909957],
       [5.30015613, 3.79080059, 2.51822614, 2.7846796 , 1.66449031],
       [5.28799321, 1.4315766 , 1.91238727, 3.97139427, 0.96457251],
       [1.85237651, 1.39289569, 2.69049145, 3.82835395, 1.24835015],
       [4.50877579, 5.83016326, 2.27062925, 3.36832302, 3.80344375]])