# Dummies

In [3]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({"x": np.arange(1, 11)})

In [12]:
y  = pd.get_dummies(df["x"]).astype(int)

In [13]:
y

1   2   3   4   5   6   7   8   9   10
0   1   0   0   0   0   0   0   0   0   0
1   0   1   0   0   0   0   0   0   0   0
2   0   0   1   0   0   0   0   0   0   0
3   0   0   0   1   0   0   0   0   0   0
4   0   0   0   0   1   0   0   0   0   0
5   0   0   0   0   0   1   0   0   0   0
6   0   0   0   0   0   0   1   0   0   0
7   0   0   0   0   0   0   0   1   0   0
8   0   0   0   0   0   0   0   0   1   0
9   0   0   0   0   0   0   0   0   0   1

# Etiquetas

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le = LabelEncoder()

In [27]:
le.fit(["paris", "paris", "tokyo", "amsterdam"])

LabelEncoder()

In [28]:
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [29]:
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

# Estandarización Min-Max

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [32]:
scaler = MinMaxScaler()

In [35]:
scaler.fit(data)

MinMaxScaler()

In [40]:
scaler.data_max_, scaler.data_min_

(array([ 1., 18.]), array([-1.,  2.]))

In [41]:
print(scaler.transform(data))

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [42]:
print(scaler.transform([[2, 2]]))

[[1.5 0. ]]


# Binarizar

In [15]:
from sklearn.preprocessing import Binarizer

In [22]:
X = [
    [1.0, -1.0,  2.0],
    [2.0,  0.0,  0.0],
    [0.0,  1.0, -1.0]
]

In [23]:
transformer  = Binarizer().fit(X)
Y = transformer.transform(X)

In [24]:
Y

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])